bases:
- ../base
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
## Enable the line below if a secrets.enc.yaml is created in this directory
# - secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    interval: 1m
# Use the following three lines to test a new version of Big Bang without affecting other environments
#    ref:
#      $patch: replace
#      semver: "1.9.0"
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: bigbang
  spec:
    interval: 1m